# Generated by Django 6.0.1 on 2026-01-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_policy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_date', models.DateField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_reminders', to='my_app.policy')),
            ],
        ),
    ]
